### ISSUE TITLE
singer_sdk.exceptions.FatalAPIError: 403 Client Error: Forbidden for path: /v14/customers:listAccessibleCustomers

### ISSUE THREAD

**Issue by Gautam-Kundalia** [Matatika/tap-googleads#27]
I have recently started working with Meltano and attempted to integrate Google Ads as a Tap. While the authorization process was successful, I repeatedly encountered an error that I have been unable to resolve. I referred to the Google Docs, which provided the following cURL command for accessing the Google Ads API:

`curl -f --request GET "https://googleads.googleapis.com/v${API_VERSION}/customers:listAccessibleCustomers" \
--header "Content-Type: application/json" \
--header "developer-token: ${DEVELOPER_TOKEN}" \
--header "Authorization: Bearer ${OAUTH2_ACCESS_TOKEN}" \`

This command works as expected when executed directly. However, I am uncertain about how to incorporate this into Meltano to properly configure the Google Ads Tap.

Steps to Reproduce:

1)Followed the Meltano documentation to set up the Google Ads Tap.
2)Successfully completed the authorization process.
3)Encountered an error during the data extraction phase.

**Comment by ReubenFrankel** [comment]
Can you share your config?

**Comment by tobiascadee** [comment]
I have the same problem!

**Comment by ReubenFrankel** [comment]
The minimum required config for most use-cases is:
- `customer_id`
- `developer_token`
- `oauth_credentials.client_id`
- `oauth_credentials.client_secret`
- `oauth_credentials.refresh_token`

An access token is generated by the tap during runtime use the provided OAuth credentials (client ID, client secret and refresh token), and is not understood as a config option currently (assuming that is what `OAUTH2_ACCESS_TOKEN` above is referencing) - perhaps documentation could do with updating here.

**Comment by ReubenFrankel** [comment]
@Gautam-Kundalia @tobiascadee Would either of you be able verify the above approach?

**Comment by ReubenFrankel** [comment]
Closing for now as there isn't much to go off here. Please reopen if you are still experiencing this issue.
