### ISSUE TITLE
update `singer_sdk` version

### ISSUE THREAD

**Issue by tobiascadee** [Matatika/tap-googleads#40]
It seems like this tap has parent child logic built in that it does not use. If the `singer_sdk` can be updated to the latest version there is an option to override `generate_child_contexts` to allow for a child stream per accessible customer.

**Comment by tobiascadee** [comment]
@DanielPDWalker would this be possible? I think the only reason not to is to support python version 3.7

**Comment by DanielPDWalker** [comment]
Python 3.7 is end of life anyway so dropping support seems reasonable. Plus we have GitHub release people can pin to if they need to use a version that works with 3.7.

So I don't think there is anything stopping this change.
